# Generated by Django 4.2.1 on 2023-06-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aerolinea_codigos_demora_plantilla_turnaround_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maquinaria',
            new_name='maquinaria',
        ),
    ]
